name: task1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  html: ^0.15.1
  transparent_image: ^2.0.0
  image_pixels: ^3.0.0
  url_launcher: ^6.1.6
  http: ^0.13.5
  flutter_svg: ^1.1.6
  gradient_like_css: ^1.0.1

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/json/topstore.json
    - assets/images/logo.png
    - assets/right_arrow.svg
    - assets/icon_friends.svg
    - assets/home.svg
    - assets/menu.svg
    - assets/portfolio.svg
    - assets/shop.svg
    - assets/notification.svg
    - assets/search.svg

  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
